image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      psql -h localhost -d postgres << EOF
        create database baserow;
        create user baserow with encrypted password 'yourpassword';
        grant all privileges on database baserow to baserow;
      EOF
      pip3 install --no-warn-script-location \
        -r /workspace/baserow/backend/requirements/base.txt \
        -r /workspace/baserow/backend/requirements/dev.txt
      python3 /workspace/baserow/backend/src/baserow/manage.py migrate
    command: |
      python3 /workspace/baserow/backend/src/baserow/manage.py runserver 0.0.0.0:8000
  - init: |
      (cd web-frontend && yarn install)
      (cd web-frontend && yarn run build)
    command: |
      (cd web-frontend && yarn run dev)


ports:
  - port: 5432
    onOpen: ignore
  - port: 8000
    onOpen: ignore
  - port: 3000
    onOpen: open-preview
